In [1]:
# Dependencies
from matplotlib import pyplot as plt
from scipy.stats import linregress
import numpy as np
from sklearn import datasets
import pandas as pd
from pprint import pprint

In [2]:
# Import data from CSV's
grocery_data = pd.read_csv('Resources/grocery_consumption_19_20.csv')
grocery_data

,Grocery Consumption Category,2019M01,2019M02,2019M03,2019M04,2019M05,2019M06,2019M07,2019M08,2019M09,...,2019M12,2020M01,2020M02,2020M03,2020M04,2020M05,2020M06,2020M07,2020M08,2020M09
0,Cereals and bakery products,142349,139160,140742,141714,141374,142700,143963,144391,142633,...,142791,143562,143129,177724,150935,155017,153845,155114,153090,152942
1,Meats and poultry,162972,158595,161825,161893,161123,162745,164394,164896,163265,...,160863,160228,159684,201253,170529,167545,162020,168507,168277,169222
2,Fish and seafood,13586,13216,13567,13808,13676,13909,14027,13986,13882,...,13826,13630,13633,17109,14597,15070,15109,15103,14857,14770
3,Milk dairy products and eggs,89712,88129,89066,89515,89484,89969,90692,90802,89287,...,88958,88590,88048,109224,92285,94312,94746,96189,93489,94164
4,Fats and oils,23724,23232,23513,23978,23663,23900,24337,24396,24194,...,24352,24033,24097,30268,26117,26721,26477,26602,26164,26235
5,Fresh fruits and vegetables,83285,81046,81457,82412,83093,84110,84757,84883,84974,...,85618,85193,85144,106379,92262,93807,92650,92934,91172,91742
6,Processed fruits and vegetables,30991,29927,30011,30430,30456,30551,30996,31034,30746,...,30499,30639,30674,38355,32704,33378,32978,33136,32600,32502
7,Sugar and sweets,47493,46588,46787,47761,47776,47296,47721,47710,46768,...,47554,46298,46657,55010,46998,47971,48736,49524,48475,48231
8,Food products not elsewhere classified,151454,147410,150119,150769,151744,151673,153970,153530,152588,...,153434,153724,151106,184953,157001,161062,160482,161763,158760,160188
9,Coffee tea and other beverage materials,17512,17122,17365,17435,17466,17398,17700,17700,17595,...,17729,17821,17620,21714,18745,19244,18977,19419,18990,19086
10,Mineral waters soft drinks and veget...,79929,78135,79089,80286,79990,81172,81997,82116,81365,...,81062,80450,80513,93803,77717,79528,80522,82449,81381,81962
11,Alcoholic beverages purchased for of...,136945,135327,137409,137883,137812,138454,138946,139186,138987,...,140646,140755,140676,165833,148111,157300,157851,157749,158567,158632

In [3]:
grocery_data.columns

Index(['Grocery Consumption Category ', '2019M01', '2019M02', '2019M03',
       '2019M04', '2019M05', '2019M06', '2019M07', '2019M08', '2019M09',
       '2019M10', '2019M11', '2019M12', '2020M01', '2020M02', '2020M03',
       '2020M04', '2020M05', '2020M06', '2020M07', '2020M08', '2020M09'],
      dtype='object')

In [4]:
grocery_data2019 = grocery_data.loc[:,['Grocery Consumption Category ','2019M01', '2019M02', '2019M03',
       '2019M04', '2019M05', '2019M06', '2019M07', '2019M08', '2019M09',
       '2019M10', '2019M11', '2019M12']]
                                    
grocery_data2019

grocery_data2020 = grocery_data.loc[:,['Grocery Consumption Category ','2020M01', '2020M02', '2020M03',
       '2020M04', '2020M05', '2020M06', '2020M07', '2020M08', '2020M09']]
grocery_data2020

,Grocery Consumption Category,2020M01,2020M02,2020M03,2020M04,2020M05,2020M06,2020M07,2020M08,2020M09
0,Cereals and bakery products,143562,143129,177724,150935,155017,153845,155114,153090,152942
1,Meats and poultry,160228,159684,201253,170529,167545,162020,168507,168277,169222
2,Fish and seafood,13630,13633,17109,14597,15070,15109,15103,14857,14770
3,Milk dairy products and eggs,88590,88048,109224,92285,94312,94746,96189,93489,94164
4,Fats and oils,24033,24097,30268,26117,26721,26477,26602,26164,26235
5,Fresh fruits and vegetables,85193,85144,106379,92262,93807,92650,92934,91172,91742
6,Processed fruits and vegetables,30639,30674,38355,32704,33378,32978,33136,32600,32502
7,Sugar and sweets,46298,46657,55010,46998,47971,48736,49524,48475,48231
8,Food products not elsewhere classified,153724,151106,184953,157001,161062,160482,161763,158760,160188
9,Coffee tea and other beverage materials,17821,17620,21714,18745,19244,18977,19419,18990,19086
10,Mineral waters soft drinks and veget...,80450,80513,93803,77717,79528,80522,82449,81381,81962
11,Alcoholic beverages purchased for of...,140755,140676,165833,148111,157300,157851,157749,158567,158632

In [5]:
grocery_data2019['2019 Total']=grocery_data2019.sum(axis=1)
grocery_data2019
grocery_data2019 = grocery_data2019.rename(columns={'Grocery Consumption Category ': 'Grocery Consumption Category','2019M01': 'Jan', '2019M02':'Feb', '2019M03':'Mar',
       '2019M04':'Apr', '2019M05':'May', '2019M06':'Jun', '2019M07':'Jul', '2019M08':'Aug', '2019M09':'Sep', '2019M10': 'Oct',
                                '2019M11': 'Nov','2019M12':'Dec'})


grocery_data2020['2020 Total']=grocery_data2020.sum(axis=1)
grocery_data2020.columns


grocery_data2020 = grocery_data2020.rename(columns={'Grocery Consumption Category ': 'Grocery Consumption Category','2020M01': 'Jan', '2020M02':'Feb', '2020M03':'Mar',
       '2020M04':'Apr', '2020M05':'May', '2020M06':'Jun', '2020M07':'Jul', '2020M08':'Aug', '2020M09':'Sep'})

In [6]:
grocery_data2019.columns

Index(['Grocery Consumption Category', 'Jan', 'Feb', 'Mar', 'Apr', 'May',
       'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', '2019 Total'],
      dtype='object')

In [7]:
grocery_data2019['Grocery Consumption Category']=grocery_data2019['Grocery Consumption Category'].str.lstrip()
grocery_data2020['Grocery Consumption Category']=grocery_data2020['Grocery Consumption Category'].str.lstrip()

In [8]:
grocery_data2019.reset_index()

,index,Grocery Consumption Category,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,2019 Total
0,0,Cereals and bakery products,142349,139160,140742,141714,141374,142700,143963,144391,142633,142962,142816,142791,1707595
1,1,Meats and poultry,162972,158595,161825,161893,161123,162745,164394,164896,163265,162487,162542,160863,1947600
2,2,Fish and seafood,13586,13216,13567,13808,13676,13909,14027,13986,13882,13746,13867,13826,165096
3,3,Milk dairy products and eggs,89712,88129,89066,89515,89484,89969,90692,90802,89287,89444,89189,88958,1074247
4,4,Fats and oils,23724,23232,23513,23978,23663,23900,24337,24396,24194,24197,24202,24352,287688
5,5,Fresh fruits and vegetables,83285,81046,81457,82412,83093,84110,84757,84883,84974,84823,85240,85618,1005698
6,6,Processed fruits and vegetables,30991,29927,30011,30430,30456,30551,30996,31034,30746,30591,30527,30499,366759
7,7,Sugar and sweets,47493,46588,46787,47761,47776,47296,47721,47710,46768,47024,46936,47554,567414
8,8,Food products not elsewhere classified,151454,147410,150119,150769,151744,151673,153970,153530,152588,152720,152409,153434,1821820
9,9,Coffee tea and other beverage materials,17512,17122,17365,17435,17466,17398,17700,17700,17595,17666,17510,17729,210198
10,10,Mineral waters soft drinks and vegetable juices,79929,78135,79089,80286,79990,81172,81997,82116,81365,81678,80989,81062,967808
11,11,Alcoholic beverages purchased for off-premises...,136945,135327,137409,137883,137812,138454,138946,139186,138987,139374,140546,140646,1661515

In [9]:
# grocery_data2019 = grocery_data2019.transpose()
# grocery_data2020 = grocery_data2019.transpose()
# grocery_data2019

In [10]:
# x = grocery_data2019['Cereals and bakery products']
# y = grocery_data2020['Cereals and bakery products']

# plt.scatter(x,y)
# plt.show()